### ISSUE TITLE
It is not clear how to choose between AND and OR search

### ISSUE THREAD

**Issue by lincredibleJC** [CS2103AUG2017-T09-B3/main#153] opened 2017-11-04 07:31 UTC
It is not clear how to choose between AND and OR search.
The app is permanently in OR search.

![image](https://user-images.githubusercontent.com/22949932/32403459-e8a0c186-c174-11e7-8d2e-8c93b369cd99.png)

Suggestion:
Add examples to show how to select AND or OR search.

**Comment by yunpengn** [comment] 2017-11-04 09:45
Close this because it is a duplicate of https://github.com/CS2103AUG2017-T09-B3/main/issues/142.

The changes will be included in the next release. `AND` search has not been implemented yet.

Thanks for bug reporting. We have to close this because it will be troublesome for everyone when the issue list has a lot of duplicates.

**Closed as completed by yunpengn** 2017-11-04 09:45 UTC
Labels: priority.low
