### ISSUE TITLE
Person Contact details are not consistent

### ISSUE THREAD

**Issue by lincredibleJC** [CS2103AUG2017-T09-B3/main#152] opened 2017-11-04 07:23 UTC
The Name, Email, Phone and Address fields are in different orders for different people.

![image](https://user-images.githubusercontent.com/22949932/32403422-0bdd5340-c174-11e7-9ec7-768f31383cda.png)
![image](https://user-images.githubusercontent.com/22949932/32403423-10530c8a-c174-11e7-9a6d-848cc745ea09.png)
![image](https://user-images.githubusercontent.com/22949932/32403424-151b1b2c-c174-11e7-8a84-9a249f262d19.png)

**Comment by yunpengn** [comment] 2017-11-04 09:48
Close this because it is a duplicate of https://github.com/CS2103AUG2017-T09-B3/main/issues/141.


It has been fixed. The changes will be included in the next release.

**Closed as completed by yunpengn** 2017-11-04 09:48 UTC
Labels: type.bug
